monolog:
    channels:
        - deprecation
        - security  # add a separate security channel

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!doctrine", "!console"]

            security:
                type: stream
                path: "%kernel.logs_dir%/security.log"
                level: debug
                channels: ["security"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
